name: like_picsart
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  elementary: ^2.0.0
  provider: ^6.1.1
  auto_route: ^7.8.4
  intl: ^0.18.1
  image_picker: ^1.0.7
  bitmap: ^0.2.0
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^7.3.2

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
